#!/usr/bin/env python3
"""Generate the bounded grayscale wind-dashboard font assets."""

import argparse
import hashlib
from pathlib import Path
import tempfile

from PIL import ImageFont
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

GLYPHS = "".join(chr(value) for value in range(32, 127)) + (
    "°′″…ÀÁÄÇÈÉËÌÍÏÑÒÓÖÙÚÜàáäçèéëìíïñòóöùúü"
)

SPECS = (
    ("berkeley_mono_bold", 15, "Bold"),
    ("berkeley_mono_bold_condensed", 12, "Bold Condensed"),
    ("berkeley_mono_bold_condensed", 15, "Bold Condensed"),
    ("inter", 43, "Black"),
)


def source_hash(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_with_plain_zero(source, variation):
    font = TTFont(source)
    coordinates = next(
        instance.coordinates for instance in font["fvar"].instances
        if font["name"].getDebugName(instance.subfamilyNameID) == variation
    )
    font = instantiateVariableFont(font, coordinates, inplace=False)

    glyph_set = font.getGlyphSet()
    recording = DecomposingRecordingPen(glyph_set)
    glyph_set["zero"].draw(recording)

    contours = []
    current = []
    for operation, points in recording.value:
        current.append((operation, points))
        if operation in ("closePath", "endPath"):
            contours.append(current)
            current = []

    # Berkeley's default zero is built from a small center dot followed by
    # the outer and inner zero contours. Preserve the typeface's own zero
    # shape and metrics while removing only that center dot.
    plain_zero_pen = TTGlyphPen(glyph_set)
    for contour in contours[1:]:
        for operation, points in contour:
            getattr(plain_zero_pen, operation)(*points)
    font["glyf"]["zero"] = plain_zero_pen.glyph()

    temporary = tempfile.NamedTemporaryFile(suffix=".ttf", delete=False)
    temporary.close()
    font.save(temporary.name)
    return Path(temporary.name)


def emit_asset(output_dir, family, pixel_size, variation, source, source_name):
    render_source = source
    if family == "berkeley_mono_bold_condensed":
        render_source = source_with_plain_zero(source, variation)

    font = ImageFont.truetype(str(render_source), pixel_size)
    if render_source == source:
        font.set_variation_by_name(variation)
    ascent, descent = font.getmetrics()
    glyphs = []
    bitmap = bytearray()
    for character in sorted(set(GLYPHS), key=ord):
        mask, offset = font.getmask2(character, mode="L", anchor="ls")
        glyphs.append(
            (ord(character), len(bitmap), mask.size[0], mask.size[1],
             offset[0], offset[1], int(font.getlength(character) + 0.5))
        )
        bitmap.extend(bytes(mask))

    symbol = f"wind_font_{family}_{pixel_size}"
    fallback_index = next(i for i, glyph in enumerate(glyphs) if glyph[0] == ord("?"))
    lines = [
        "/* Generated by generate_fonts.py; do not edit. */",
        f"/* Source: {source_name}; sha256={source_hash(source)}; {variation}, {pixel_size}px"
        f"{', custom plain zero' if render_source != source else ''}. */",
        '#include "wind_font_internal.h"',
        "",
        f"static const wind_font_glyph_t {symbol}_glyphs[] = {{",
    ]
    for glyph in glyphs:
        lines.append("    {%d, %d, %d, %d, %d, %d, %d}," % glyph)
    lines.extend(("};", "", f"static const uint8_t {symbol}_bitmap[] = {{"))
    for start in range(0, len(bitmap), 16):
        chunk = bitmap[start:start + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    lines.extend((
        "};",
        "",
        f"{'static ' if pixel_size == 58 else ''}const wind_font_asset_t {symbol} = {{",
        f"    {pixel_size}, {ascent}, {descent}, {symbol}_glyphs,",
        f"    sizeof({symbol}_glyphs) / sizeof({symbol}_glyphs[0]),",
        f"    {fallback_index}, {symbol}_bitmap,",
        "};",
        "",
    ))
    suffix = ".inc" if pixel_size == 58 else ".c"
    (output_dir / f"{family}_{pixel_size}{suffix}").write_text("\n".join(lines), encoding="ascii")
    if render_source != source:
        render_source.unlink()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--berkeley", type=Path, required=True)
    parser.add_argument("--inter", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).parent)
    args = parser.parse_args()
    inter = args.inter if args.inter and args.inter.is_file() else args.berkeley
    inter_name = "InterVariable.ttf" if inter != args.berkeley else "Berkeley Mono deterministic Inter fallback"
    args.output.mkdir(parents=True, exist_ok=True)
    for family, pixel_size, variation in SPECS:
        is_berkeley = family.startswith("berkeley_mono")
        source = args.berkeley if is_berkeley else inter
        source_name = "Berkeley Mono Variable.ttf" if is_berkeley else inter_name
        emit_asset(args.output, family, pixel_size, variation, source, source_name)


if __name__ == "__main__":
    main()
