// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb2025/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb2025
//     --tz_version 2025b
//     --actions zonedb
//     --language c
//     --scope complete
//     --db_namespace Zonedb2025
//     --start_year 2025
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025b
//
// Supported Zones: 597 (340 zones, 257 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2025,2200]
// Accurate Years: [2025,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1967,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1967,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 597
//   Eras: 345
//   Policies: 66
//   Rules: 343
//
// Memory (8-bits):
//   Context: 20
//   Rules: 4116
//   Policies: 198
//   Eras: 5175
//   Zones: 4420
//   Links: 3341
//   Registry: 1194
//   Formats: 196
//   Letters: 35
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 27789
//
// Memory (32-bits):
//   Context: 28
//   Rules: 4116
//   Policies: 528
//   Eras: 6900
//   Zones: 8160
//   Links: 6168
//   Registry: 2388
//   Formats: 196
//   Letters: 49
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 37627
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ZONEDB2025_ZONE_REGISTRY_H
#define ACE_TIME_C_ZONEDB_ZONEDB2025_ZONE_REGISTRY_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

// Zones
#define kAtcZonedb2025ZoneRegistrySize 340
extern const AtcZoneInfo * const kAtcZonedb2025ZoneRegistry[340];

// Zones and Links
#define kAtcZonedb2025ZoneAndLinkRegistrySize 597
extern const AtcZoneInfo * const kAtcZonedb2025ZoneAndLinkRegistry[597];

#ifdef __cplusplus
}
#endif

#endif
