// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeSuite/compiler/src/acetimecompiler/tzcompiler.py
//     --input_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb2025/tzfiles
//     --output_dir /home/brian/src/AceTimeSuite/libraries/acetimec/src/zonedb2025
//     --tz_version 2025b
//     --actions zonedb
//     --language c
//     --scope complete
//     --db_namespace Zonedb2025
//     --start_year 2025
//     --until_year 2200
//     --nocompress
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2025b
//
// Supported Zones: 597 (340 zones, 257 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2025,2200]
// Accurate Years: [2025,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1967,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1967,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 597
//   Eras: 345
//   Policies: 66
//   Rules: 343
//
// Memory (8-bits):
//   Context: 20
//   Rules: 4116
//   Policies: 198
//   Eras: 5175
//   Zones: 4420
//   Links: 3341
//   Registry: 1194
//   Formats: 196
//   Letters: 35
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 27789
//
// Memory (32-bits):
//   Context: 28
//   Rules: 4116
//   Policies: 528
//   Eras: 6900
//   Zones: 8160
//   Links: 6168
//   Registry: 2388
//   Formats: 196
//   Letters: 49
//   Fragments: 0
//   Names: 9094 (original: 9094)
//   TOTAL: 37627
//
// DO NOT EDIT

#ifndef ACE_TIME_C_ZONEDB_ZONEDB2025_ZONE_POLICIES_H
#define ACE_TIME_C_ZONEDB_ZONEDB2025_ZONE_POLICIES_H

#include "../zoneinfo/zone_info.h"

#ifdef __cplusplus
extern "C" {
#endif

//---------------------------------------------------------------------------
// Supported policies: 66
//---------------------------------------------------------------------------

extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAN;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAQ;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAS;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAT;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAV;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAW;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyArg;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyArmenia;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAus;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyAzer;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyBarb;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyBelize;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyBrazil;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyCO;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyCR;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyCanada;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyChatham;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyChile;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyCook;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyCuba;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyDhaka;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyEU;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyEUAsia;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyEcuador;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyEgypt;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyEire;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyFiji;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyGuat;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyHK;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyHaiti;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyHoliday;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyHond;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyIran;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyIraq;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyJapan;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyLH;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyLebanon;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyMacau;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyMauritius;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyMexico;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyMoldova;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyMongol;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyMorocco;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyNC;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyNZ;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyNamibia;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyNic;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyPRC;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyPakistan;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyPalestine;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyPara;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyPeru;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyPhil;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyROK;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicySA;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicySalv;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyTaiwan;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyThule;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyTonga;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyTroll;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyTunisia;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyUS;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyUruguay;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyVanuatu;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyWS;
extern const AtcZonePolicy kAtcZonedb2025ZonePolicyZion;


//---------------------------------------------------------------------------
// Unsupported zone policies: 68
//---------------------------------------------------------------------------

// Albania {unused}
// Algeria {unused}
// Austria {unused}
// Belgium {unused}
// Bermuda {unused}
// Bulg {unused}
// C-Eur {unused}
// CA {unused}
// Chicago {unused}
// Cyprus {unused}
// Czech {unused}
// DR {unused}
// Denver {unused}
// Detroit {unused}
// E-Eur {unused}
// E-EurAsia {unused}
// Edm {unused}
// EgyptAsia {unused}
// Falk {unused}
// Finland {unused}
// France {unused}
// GB-Eire {unused}
// Germany {unused}
// Greece {unused}
// Guam {unused}
// Halifax {unused}
// Hungary {unused}
// Indianapolis {unused}
// Italy {unused}
// Jordan {unused}
// Kyrgyz {unused}
// Latvia {unused}
// Libya {unused}
// Louisville {unused}
// Malta {unused}
// Marengo {unused}
// Menominee {unused}
// Moncton {unused}
// NBorneo {unused}
// NT_YK {unused}
// NYC {unused}
// Perry {unused}
// Pike {unused}
// Poland {unused}
// Port {unused}
// Pulaski {unused}
// Regina {unused}
// Romania {unused}
// Russia {unused}
// RussiaAsia {unused}
// SanLuis {unused}
// Shang {unused}
// SovietZone {unused}
// Spain {unused}
// SpainAfrica {unused}
// StJohns {unused}
// Starke {unused}
// Sudan {unused}
// Swift {unused}
// Swiss {unused}
// Syria {unused}
// Toronto {unused}
// Turkey {unused}
// Vanc {unused}
// Vincennes {unused}
// W-Eur {unused}
// Winn {unused}
// Yukon {unused}


//---------------------------------------------------------------------------
// Notable zone policies: 6
//---------------------------------------------------------------------------

// Belize {LETTER 'CST' not single character}
// Eire {SAVE '-1:00' is a negative DST}
// LH {SAVE '0:30' different from 1:00}
// Morocco {SAVE '-1:00' is a negative DST}
// Namibia {LETTER 'CAT' not single character}
// Troll {
//   LETTER '+00' not single character,
//   LETTER '+02' not single character,
//   SAVE '2:00' different from 1:00,
// }


//---------------------------------------------------------------------------

#ifdef __cplusplus
}
#endif

#endif
