#ifndef BOARD_SEEEDSTUDIO_RETERMINAL_E100X_H
#define BOARD_SEEEDSTUDIO_RETERMINAL_E100X_H

#include "driver/gpio.h"

#define BOARD_HAL_NAME "seeedstudio_reterminal_e100x"
#define BOARD_HAL_TYPE BOARD_TYPE_SEEEDSTUDIO_RETERMINAL_E100X

#define BOARD_HAL_WAKEUP_KEY GPIO_NUM_3
#define BOARD_HAL_WAKEUP_KEY_NAME "Green Refresh Button"
#define BOARD_HAL_ROTATE_KEY GPIO_NUM_5
#define BOARD_HAL_CLEAR_KEY GPIO_NUM_4

// Shared E1001/E1002 carrier buses. Panel behavior is deliberately absent
// here and belongs to the runtime-selected backend.
#define BOARD_HAL_SPI_SCLK_PIN GPIO_NUM_7
#define BOARD_HAL_SPI_MOSI_PIN GPIO_NUM_9
#define BOARD_HAL_SPI_MISO_PIN GPIO_NUM_8
#define BOARD_HAL_EPD_DC_PIN GPIO_NUM_11
#define BOARD_HAL_EPD_CS_PIN GPIO_NUM_10
#define BOARD_HAL_EPD_RST_PIN GPIO_NUM_12
#define BOARD_HAL_EPD_BUSY_PIN GPIO_NUM_13

#define BOARD_HAL_SD_PWR_PIN GPIO_NUM_16
#define BOARD_HAL_SD_CS_PIN GPIO_NUM_14
#define BOARD_HAL_I2C_SDA_PIN GPIO_NUM_19
#define BOARD_HAL_I2C_SCL_PIN GPIO_NUM_20
#define BOARD_HAL_CHARGER_I2C_SDA_PIN GPIO_NUM_39
#define BOARD_HAL_CHARGER_I2C_SCL_PIN GPIO_NUM_40
#define BOARD_HAL_BAT_ADC_PIN ADC_CHANNEL_0
#define BOARD_HAL_BAT_EN_PIN GPIO_NUM_21
#define BOARD_HAL_LED_PIN GPIO_NUM_6
#define BOARD_HAL_LED_INVERTED true
#define BOARD_HAL_DISPLAY_ROTATION_DEG 0

#endif
